Parameters:
  RoleTempName: 
    Description: Name of the base stack with all infra resources
    Type: String
    Default: cicds3role
  JenkStackName:
    Description: Name of the base stack with all infra resources
    Type: String
    Default: jenk
  MyIP:
    Type: String
  KeyName:
    Type: String
  InstanceType:
    Type: String
    Default: t2.micro

Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: ami-0bba7e961f185c2e2
    us-east-2:
      AMI: ami-05a6ffc039efb874d
    us-west-1:
      AMI: ami-0bba7e961f185c2e2
    us-west-2:
      AMI: ami-0bba7e961f185c2e2
    eu-central-1:
      AMI: ami-054348ac63eaf375f

Resources:
  App01qaInst:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join ["", ["app01qa in ", !Ref AWS::Region]]
      SecurityGroups:
        - !Ref VproappSG
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: "${RoleTempName}-VPS3RoleProfileName"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt update
            sudo apt install openjdk-8-jdk -y
            sudo apt install git wget unzip maven -y
            sudo apt install awscli -y
            TOMURL="https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz"
            cd /tmp/
            wget $TOMURL -O tomcatbin.tar.gz
            EXTOUT=`tar xzvf tomcatbin.tar.gz`
            TOMDIR=`echo $EXTOUT | cut -d '/' -f1`
            sudo useradd --shell /sbin/nologin tomcat
            sudo rsync -avzh /tmp/$TOMDIR/ /usr/local/tomcat8/
            # aws s3 cp s3://vprofile-cicd-stack-last-course/tomcat-users.xml /usr/local/tomcat8/conf/tomcat-users.xml
            # aws s3 cp s3://vprofile-cicd-stack-last-course/context.xml /usr/local/tomcat8/webapps/manager/META-INF/context.xml
            sudo chown -R tomcat.tomcat /usr/local/tomcat8 
            sudo cat <<EOT>> /etc/systemd/system/tomcat.service
            [Unit]
            Description=Tomcat
            After=network.target

            [Service]
            User=tomcat
            WorkingDirectory=/usr/local/tomcat8
            Environment=CATALINA_HOME=/usr/local/tomcat8
            Environment=CATALINE_BASE=/usr/local/tomcat8
            ExecStart=/usr/local/tomcat8/bin/catalina.sh run
            ExecStop=/usr/local/tomcat8/bin/shutdown.sh
            SyslogIdentifier=tomcat-%i

            [Install]
            WantedBy=multi-user.target
            EOT

            sudo systemctl daemon-reload
            sudo systemctl start tomcat
            sudo systemctl enable tomcat

            git clone -b local-setup https://github.com/devopshydclub/vprofile-project.git
            cd vprofile-project
            mvn install
            sudo systemctl stop tomcat
            sleep 60
            sudo rm -rf /usr/local/tomcat8/webapps/ROOT*
            sudo cp target/vprofile-v2.war /usr/local/tomcat8/webapps/ROOT.war
            sudo systemctl start tomcat
            sleep 120
            sudo cp /vagrant/application.properties /usr/local/tomcat8/webapps/ROOT/WEB-INF/classes/application.properties
            sudo systemctl restart tomcat

  VproappSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from myip
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  VproappSGIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt VproappSG.GroupId
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8080
      SourceSecurityGroupId: 
        Fn::ImportValue: 
          Fn::Sub: "${JenkStackName}-SGID"

Outputs:
  AppSecurityGroupId:
    Description: Security Group 1 ID
    Value: !GetAtt VproappSG.GroupId
    Export:
      Name: app01qa-SGID