Parameters:
  RoleTempName: 
    Description: Name of the base stack with all infra resources
    Type: String
    Default: cicds3role
  MyIP:
    Type: String
  KeyName:
    Type: String
  InstanceType:
    Type: String
    Default: t2.small

Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: ami-0bba7e961f185c2e2
    us-east-2:
      AMI: ami-05a6ffc039efb874d
    us-west-1:
      AMI: ami-0bba7e961f185c2e2
    us-west-2:
      AMI: ami-0bba7e961f185c2e2
    eu-central-1:
      AMI: ami-054348ac63eaf375f

Resources:
  JenkinsInst:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join ["", ["Jenkins in ", !Ref AWS::Region]]
      SecurityGroups:
        - !Ref JenkinsSG
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: "${RoleTempName}-VPS3RoleProfileName"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt update
            sudo apt install openjdk-8-jre
            sudo apt install openjdk-11-jre -y
            sudo apt install maven git wget unzip -y
            sudo apt install awscli -y
            curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
            /usr/share/keyrings/jenkins-keyring.asc > /dev/null
            echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
            https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
            /etc/apt/sources.list.d/jenkins.list > /dev/null
            sudo apt-get update
            sudo apt-get install jenkins -y
            sleep 10
            sudo systemctl stop jenkins
            sleep 10
            aws s3 cp s3://vprofile-cicd-stack-last-course/jenkins_cicd_jobs.tar.gz /var/lib/
            cd /var/lib/
            tar xzvf jenkins_cicd_jobs.tar.gz
            chown jenkins.jenkins /var/lib/jenkins -R
            sudo rm -rf jenkins_cicd_jobs.tar.gz
            sudo systemctl start jenkins
            reboot 
  JenkinsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from myip
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: !Ref MyIP

Outputs:
  MyEC2InstancePublicIP:
    Value: !GetAtt JenkinsInst.PublicIp
  MyEC2InstancePrivateIP:
    Value: !GetAtt JenkinsInst.PrivateIp
  MyEC2InstanceID:
    Value: !Ref JenkinsInst
  JenkSecurityGroupId:
    Description: Security Group 1 ID
    Value: !GetAtt JenkinsSG.GroupId
    Export:
      Name: jenk-SGID